-- Table: waitlist_signups
-- Note: Supabase gives you a PostgreSQL database out of the box. You can execute this in the Supabase SQL Editor.

CREATE TABLE public.waitlist_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(50),
  practice_name VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  email_stage INTEGER DEFAULT 1 -- 1 = Welcome sent, 2 = Update sent, 3 = Launch sent
);

-- Row Level Security (optional but recommended for public facing apps)
ALTER TABLE public.waitlist_signups ENABLE ROW LEVEL SECURITY;

-- Allow service role full access (which the API routes use)
CREATE POLICY "Allow service role full access" 
ON public.waitlist_signups
FOR ALL 
USING (true) 
WITH CHECK (true);
